name: Build and Deploy Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup Azure CLI
      if: github.ref == 'refs/heads/main'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Run complete pipeline with tracking
      run: npm run pipeline
      env:
        NODE_ENV: production
        DYNATRACE_TOKEN: ${{ secrets.DYNATRACE_TOKEN }}
        DYNATRACE_ENDPOINT: ${{ secrets.DYNATRACE_ENDPOINT }}
        AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
        AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        FORCE_DEPLOY: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: pipeline-artifacts
        path: |
          dist/
          deploy.tar.gz
        retention-days: 7
